# 只保留三個一般網頁引擎；其餘預設引擎都不載入
# https://docs.searxng.org/admin/settings/settings.html#engines-keep-only
use_default_settings:
  engines:
    keep_only:
      # - duckduckgo
      - googlenews
      # - googlenews
    
# engines:
#   - name: googlenews
#     engine: googlenews
#     disabled: false

server:
  secret_key: "ultrasecretkey2ultrasecretkey"

search:
  formats:
    - html
    - json

engines:

  # --- Google News（主力） ---
  - name: googlenews
    engine: google_news
    shortcut: gon
    timeout: 8.0
    disabled: false

# 防止被 abuse（你做 API 很重要）
limiter:
  real_ip:
    header: X-Forwarded-For
  rate_limit:
    ip_limit: 5
    ip_window: 10